# Generated by Django 4.2 on 2023-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_alter_game_number_of_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='skill_level',
            field=models.CharField(max_length=50),
        ),
    ]
