# Generated by Django 4.2 on 2023-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0004_rename_creator_game_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='attended_events', to='levelupapi.gamer'),
        ),
    ]
